public class SalesforceDeveloper {

public void myFirstCode (){
    string favoriteCity = 'New York';
    string favoriteMovie = 'The Conjuring';
    string favoriteSeason = 'Summer';

    system.debug(favoriteCity);
    system.debug(favoriteMovie);
    system.debug(favoriteSeason);
    }


public void myFavorites(){
    string city = 'San Francisco';
    system.debug(city);

    integer nbr = 7;
    system.debug(nbr);

system.debug('My favorite city ==> ' + city + 'and My favorite number ==> ' + nbr);
    }
}