List<integer> listInteger = new List<integer>();
listInteger.add(10);
listInteger.add(15);
listInteger.add(21);
listInteger.add(15);
listInteger.add(15);
CalculatorSt.add(listInteger);

//for (integer eachInt : listInteger) {
            //system.debug(eachInt);
            //sum += eachInt
            //sum =sum+eachInt
         //}
       // sytem.debug(sum);







//integer sum1 = CalculatorSt.add(5, 15);
//system.debug(sum1);